name: Sync Features to Discord
on:
  push:
    branches:
      - main
    paths:
      - 'features.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Send Document Update to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: '📢 **The Features Document has been updated!** \n\n ${{ github.event.head_commit.message }}'
